language: python
python:
- '3.6'
dist: xenial
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pipenv install --dev
script:
- pipenv run python -m unittest
deploy:
  provider: pypi
  user:
    secure: q51M9ICLd7mcPlGtXwSBl+2ZPd8HkwTwb3bGSynTsCEm+nChuuYgscrW7O++2m2zNxI9AvjkEscb4IvQ76Tp78cZCvABjyKCd+dW7cdN3bupY1D7I3tT8qhT7Db2nXVMNNlxgYJpjU3+nZ8xxMYNj2ck35S9Az+ZmFqsCDdtinZSmaXsc7ZeLE/QfM7OCd/h2ueYWUSawjsQjQfVV7+3g6oBuHA2ZHCeKROlFKwbCWPfvHATS+12kyS8V74wuHzwG7mPbYvuZi2ZVxKjNFtDbhUNN7RUxeK7MphEyNSLvnoG8Voj3/xFve2J3QUr9hpSr9GpRODx4BB2lV41VweMA3zCV6u9xcriUAu6v32gHvDENfLBXfQTAQQ/vczFKOzLmQ7FeDHhB9KsKT36165BwCBWVYCXNhGHzzfB7/osyJ9cZnivlr5sENCixK4daUcVwhlOyjZ13WVEx491SYGpuqG+Jxkd2J9GwTlnl3fBG9EfqTRX2ckqJRhB3An8rCFOZffcCspuzV/eh8ntesuwodK34oRYe6nMQk79v5M5WbPX2k8GGImm+qHnNgWlTLgWr3nlPc+y71Qj0G7bFHokfZEHp3VftF20Z1UepkVZdEGjkbFD2nooGUfBCcepzrx6WYV+poBrZWHdJ3nXuSmvxAT89ut5qs7NO6nXSvn0HSk=
  password:
    secure: lhO6SQn0b0i1CcrWTslPcvV9PCuCuyF53OxaAvelLlRDL52pc3SUSrwjnYAD6AtED3hsbBSaX3IMIOSFz6BWQ7D7YsLKpNC6FVWi7W9B8Q/kjDUlf317UXbqTOduB0XSHMUaHvWRzWDUtDbdLCuNhTtH86H7FJTk5U5eEpIXIimswA78Kx5I4j5ckrtFvjJTi8ajOl2Hs7MT295EYcpa7bf0KZ4Aq5WR1TwaNOnhFbPOLnPNJKgIF2uY1eZDhJ4OsYi0vvjtWmDFzeZLStj+ZA6Mnz8BEZCCjaQBRKCH65jNeJg/lUgo0qz/tCwIKK+MPWenbPzxdLUjkx1jnwed8bSsRiiK3Ow+6XkiBbujWuP+jAdWEnoz8VjEiZWFzTbrtcH/6zBM2DKIeg1xTb5mrDQZOVQ8W/tJzs7ww3AfRQDweD/WVK6sM3AUE3kIUQeCNxzRDXunxwV5MP6cmRVc7JaCaDRmHUNnfbDHbD7wCqAzIBgu0H4fFYil7nZxYoHe8CBfNAeGl2PjEhwp8SzRvR1VZyD15uAjes2q1EqV/EQNbcw0QeiC4IvAr/svNqlr0wQgmxlgwp8dBJ1COCUm/VkyW7efE/rBEJcbnE87iyAr659g4wnedpyFCM6mNsq7u5kigITUk6CehTZYkHPYnAvZYGeTdghE2CsMwoBRZsg=
  server: https://test.pypi.org/legacy/
  distributions: sdist
  on:
    branch: master
